#!/bin/bash

if ! type inotifywait &>/dev/null ; then
	echo "The dependency 'inotifywait' is missing. Install the package inotify-tools (apt-get install inotify-tools)"
	exit 1
fi

function watchscss () {
	unbuffer compass compile --output-style compressed --force
	inotifywait --quiet -m -r -e close_write,moved_to,create sass |
	while read -r directory events filename; do
		unbuffer compass compile --output-style compressed --force
	done
}

function watchjs() {
	unbuffer npm run watch
}

esc=$(printf '\033'); WHITE='[1;37m'; GREEN='[1;32m'; BLUE='[1;34m'

trap 'kill %1' SIGINT
watchjs | sed -e "s/^/${esc}${GREEN}[Webpack]${esc}${WHITE} /" & watchscss | sed -e "s/^/${esc}${BLUE}[Compass]${esc}${WHITE} /"

trap - SIGINT
echo
